name: zflutter
description: A round, flat and designer-friendly pseudo-3D engine for Flutter
version: 0.0.1+2
homepage: https://z.flutter.gallery/
repository: https://github.com/jamesblasco/zflutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  quiver: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
